<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/**
 * cfg_users - autogenerated Table_model for table cfg_users
 * 
 * @author: Jan den Besten
 * %Generated: Thu 28 April 2016, 17:02
 * $Revision$
 * @copyright: (c) Jan den Besten
 */

Class cfg_users extends Data_Core {

  public function __construct() {
    parent::__construct();
  }

  /**
   * Aanpassing voor ->where() zodat ook 'current' opgevraagd kan worden
   *
   * @param string $key 
   * @param string $value 
   * @param string $escape 
   * @return void
   * @author Jan den Besten
   */
  public function where($key, $value = NULL, $escape = NULL) {
    if ($key==='current' and isset($this->user->user_id)) {
      $value = $this->user->user_id;
      $key = $this->settings['primary_key'];
    }
    return parent::where($key,$value,$escape);
  }

}
