<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/**
 * cfg_user_groups - autogenerated Table_model for table cfg_user_groups
 * 
 * @author: Jan den Besten
 * %Generated: Tue 17 May 2016, 17:25
 * $Revision$
 * @copyright: (c) Jan den Besten
 */

Class cfg_user_groups extends Data_Core {

  public function __construct() {
    parent::__construct();
  }
  
  
  

}
