<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/**
 * {NAME} - autogenerated Data model for table {NAME} @ {DATE}
 * 
 * @author: Jan den Besten
 * @copyright: (c) Jan den Besten
 */

Class {NAME} extends Data_Core {

  public function __construct() {
    parent::__construct();
  }

}
