<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/**
 * tbl_menu - autogenerated Data model for table tbl_menu @ Fri 10 February 2017, 16:56
 * 
 * @author: Jan den Besten
 * @copyright: (c) Jan den Besten
 */

Class tbl_menu extends Data_Core {

  public function __construct() {
    parent::__construct();
  }

}
