<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/**
 * tbl_menu - autogenerated Data model for table tbl_menu @ Fri 10 February 2017, 16:56
 * 
 * @author: Jan den Besten
 * @copyright: (c) Jan den Besten
 */

Class tbl_menu extends Data_Core {

  public function __construct() {
    parent::__construct();
  }
  
  
  /**
   * Als een pagina is verwijderd, verwijder dan alle links naar die pagina.
   *
   * @param mixed $where 
   * @param int $limit 
   * @param bool $reset_data 
   * @return mixed
   * @author Jan den Besten
   */
  public function delete( $where = '', $limit = NULL, $reset_data = TRUE ) {
    // Normale update uitvoeren
    $deleted = parent::delete( $where, $limit, $reset_data );

    // Vervang alle oude links
    if ($deleted) {
      $this->load->model('search_replace');
      $this->query_info['deleted_links'] = array();
      foreach ($deleted as $item) {
        $old_link = $item['uri'];
        $this->query_info['deleted_links'][] = $this->search_replace->links($old_link,'');
      }
    }
    
    return $deleted;
  }
  
  
  
  /**
   * Als een pagina uri is aangepast, vervang dan alle links naar die pagina.
   *
   * @param mixed $set
   * @param mixed $where
   * @param int $limit
   * @return mixed
   * @author Jan den Besten
   */
   public function update( $set = NULL, $where = NULL, $limit = NULL) {
    // Nieuwe data
    if ( !$set ) $set = $this->tm_set;

    // Wordt uri aangepast?
    $uri_source = $this->_get_uri_source_field();
    if ( $uri_source and isset($set[$uri_source])) {

      // Kan alleen als alles in update() wordt gezet
      if (!$where) throw new Exception( __CLASS__.": When updating `tbl_menu` allways set WHERE with update() method instead of where() method to make sure uri's are replaced in content.");

      // Oude uri
      $old_link = $this->_get_old_link( $where );

      // Normale update uitvoeren
      $id = parent::update( $set, $where, $limit );

      // New link
      $new_link = $this->get_field('uri',$where);

      // Vervang alle links
      if ($id and isset($old_link) and $old_link) {
       $this->load->model('search_replace');
       $this->query_info['replaced_links'] = $this->search_replace->links($old_link,$new_link);
      }
    }
    else {
      // Normale update uitvoeren
      $id = parent::update( $set, $where, $limit );
    }
    return $id;
  }
  
  
  /**
   * Haalt oude link op uit database
   *
   * @param int $id
   * @return mixed
   * @author Jan den Besten
   */
  private function _get_old_link( $id ) {
    $old_link = FALSE;
    $sql = 'SELECT `uri` FROM `'.$this->settings['table'].'` WHERE `'.$this->settings['primary_key'].'` = '.$id;
    $query = $this->db->query($sql);
    if ($query) {
      $row = $query->row_array();
      $old_link = $row['uri'];
    }
    return $old_link;
  }
  
  

}
