<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
 *--------------------------------------------------------------------------
 * Base Site URL
 *--------------------------------------------------------------------------
 *
 * URL to your CodeIgniter root. Typically this will be your base URL,
 * WITH a trailing slash:
 *
 *	http://example.com/
 *
 */

if (!isset($config['base_url'])) {
	// If no automatic base_url, comment this:
	die("sorry no automatic 'base_url', edit '".SITEPATH."config_local.php'.");
	// And uncomment this with right base_url
	// $config['base_url']	= "http://localhost/";
}

/*
 *--------------------------------------------------------------------------
 * Index File
 *--------------------------------------------------------------------------
 *
 * Typically this will be your index.php file, unless you've renamed it to
 * something else. If you are using mod_rewrite to remove the page set this
 * variable so that it is blank.
 *
 */
// $config['index_page'] = "index.php";

/*
 *--------------------------------------------------------------------------
 * URI PROTOCOL
 *--------------------------------------------------------------------------
 *
 * This item determines which server global should be used to retrieve the
 * URI string.  The default setting of "AUTO" works for most servers.
 * If your links do not seem to work, try one of the other delicious flavors:
 *
 * 'AUTO'			Default - auto detects
 * 'PATH_INFO'		Uses the PATH_INFO
 * 'QUERY_STRING'	Uses the QUERY_STRING
 * 'REQUEST_URI'		Uses the REQUEST_URI
 * 'ORIG_PATH_INFO'	Uses the ORIG_PATH_INFO
 *
 */
#$config['uri_protocol']	= "AUTO";

/*
 *--------------------------------------------------------------------------
 * URL suffix
 *--------------------------------------------------------------------------
 *
 * This option allows you to add a suffix to all URLs generated by CodeIgniter.
 * For more information please see the user guide:
 *
 * http://codeigniter.com/user_guide/general/urls.html
 */

#$config['url_suffix'] = "";

/*
 *--------------------------------------------------------------------------
 * Default Language
 *--------------------------------------------------------------------------
 *
 * This determines which set of language files should be used. Make sure
 * there is an available translation if you intend to use something other
 * than english.
 *
 */
// $config['language']	= "en";

/*
 *--------------------------------------------------------------------------
 * Default Character Set
 *--------------------------------------------------------------------------
 *
 * This determines which character set is used by default in various methods
 * that require a character set to be provided.
 *
 */
#$config['charset'] = "UTF-8";

/*
 *--------------------------------------------------------------------------
 * Rewrite PHP Short Tags
 *--------------------------------------------------------------------------
 *
 * If your PHP installation does not have short tag support enabled CI
 * can rewrite the tags on-the-fly, enabling you to utilize that syntax
 * in your view files.  Options are TRUE or FALSE (boolean)
 *
 */
#$config['rewrite_short_tags'] = FALSE;



/* End of file config.php */
/* Location: ./system/application/config/config.php */
