<flexy-grid
  type='<?=$type?>'
  api='<?=$api?>'
  name="<?=$name?>"
  title="<?=$title?>"
  offset='<?=$offset?>'
  limit="<?=$limit?>"
  order="<?=$order?>"
  filter="<?=htmlentities($filter)?>"
></flexy-grid>
