<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/**
 * cfg_sessions - autogenerated Table_model for table cfg_sessions
 * 
 * @author: Jan den Besten
 * %Generated: Tue 22 September 2015, 14:07
 * $Revision$
 * @copyright: (c) Jan den Besten
 */

Class cfg_sessions extends Table_Model {

  public function __construct() {
    parent::__construct();
  }

}
