<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/**
 * cfg_media_info - autogenerated Table_model for table cfg_media_info
 * 
 * @author: Jan den Besten
 * %Generated: Tue 22 September 2015, 14:58
 * $Revision$
 * @copyright: (c) Jan den Besten
 */

Class cfg_media_info extends Table_Model {

  public function __construct() {
    parent::__construct();
  }

}
