<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/**
 * log_stats - autogenerated Table_model for table log_stats
 * 
 * @author: Jan den Besten
 * %Generated: Tue 22 September 2015, 14:58
 * $Revision$
 * @copyright: (c) Jan den Besten
 */

Class log_stats extends Table_Model {

  public function __construct() {
    parent::__construct();
  }

}
