<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/**
 * log_login - autogenerated Table_model for table log_login
 * 
 * @author: Jan den Besten
 * %Generated: Tue 22 September 2015, 14:07
 * $Revision$
 * @copyright: (c) Jan den Besten
 */

Class log_login extends Table_Model {

  public function __construct() {
    parent::__construct();
  }

}
