<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/**
 * res_media_files - autogenerated Table_model for table res_media_files
 * 
 * @author: Jan den Besten
 * %Generated: Tue 22 September 2015, 14:07
 * $Revision$
 * @copyright: (c) Jan den Besten
 */

Class res_media_files extends Table_Model {

  public function __construct() {
    parent::__construct();
  }

}
