<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/**
 * {NAME} - autogenerated Table_model for table {NAME}
 * 
 * @author: Jan den Besten
 * Generated: {DATE}
 * $Revision$
 * @copyright: (c) Jan den Besten
 */

Class {NAME} extends Table_Model {

{SETTINGS}

  public function __construct() {
    parent::__construct();
  }

}
