<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/**
 * tbl_menu - autogenerated Table_model for table tbl_menu
 * 
 * @author: Jan den Besten
 * %Generated: Thu 17 September 2015, 11:47
 * $Revision$
 * @copyright: (c) Jan den Besten
 */

Class tbl_menu extends Table_Model {

	// SETTINGS
  protected $table            = 'tbl_menu';
  protected $primary_key      = PRIMARY_KEY;
  protected $result_key       = PRIMARY_KEY;
  protected $fields           = array('id','order','self_parent','uri','str_title','txt_text','str_module','stx_description','str_keywords');
  protected $field_info       = array(
		'id'              => array('validation' => 'trim|integer|required' ), 
		'order'           => array('validation' => 'trim' ), 
		'self_parent'     => array('validation' => 'trim|integer' ), 
		'uri'             => array('validation' => 'trim|max_length[100]' ), 
		'str_title'       => array('validation' => 'required|max_length[255]' ), 
		'txt_text'        => array('validation' => '' ), 
		'str_module'      => array('validation' => 'max_length[30]|valid_option[,forms.contact,example]', 'options' => '|forms.contact|example', 'multiple_options' => false ), 
		'stx_description' => array('validation' => '' ), 
		'str_keywords'    => array('validation' => 'max_length[255]' ), 
	);
  protected $order_by         = 'order';
  protected $max_rows         = 0;
  protected $update_uris      = true;
  protected $abstract_fields  = array('str_title','str_module');
  protected $abstract_filter  = '';
  protected $admin_grid       = array(
		'fields'        => array('id','order','self_parent','uri','str_title','txt_text','str_module'), 
		'order_by'      => 'order', 
		'with'          => array(''), 
		'jump_to_today' => true, 
	);
  protected $admin_form        = array(
		'fields'    => array('id','order','self_parent','uri','str_title','txt_text','str_module','stx_description','str_keywords'), 
		'with'      => array(''), 
		'fieldsets' => array('Extra' => array('str_module','stx_description','str_keywords') ), 
	);
  // --SETTINGS


  public function __construct() {
    parent::__construct();
  }

}
