<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/**
 * tbl_menu - autogenerated Table_model for table tbl_menu
 * 
 * @author: Jan den Besten
 * Generated: Sat 12 September 2015, 00:07
 * $Revision$
 * @copyright: (c) Jan den Besten
 */

Class tbl_menu extends Table_Model {

  protected $table            = 'tbl_menu';
  protected $fields           = array('id','order','self_parent','uri','str_title','txt_text','str_module','stx_description','str_keywords');
  protected $order_by         = '';
  protected $relations        = array(
                                  'belongs_to'       => array(),
                                  'many_to_many'     => array(),
                                );
  protected $max_rows         = '0';
  protected $update_uris      = true;
  protected $abstract_fields  = array();
  protected $abstract_filter  = '';
  protected $admin_grid       = array(
                                  'fields'            => array(),
                                  'relations'         => array(),
                                  'order_by'          => '',
                                  'jump_to_today'     => TRUE,
                                );
  protected $admin_form        = array(
                                  'fields'            => array(),
                                  'relations'         => array(),
                                  'fieldsets'         => array(),
                                );
  

  public function __construct() {
    parent::__construct();
  }

}
